version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cmms
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: ./api
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/cmms
    ports:
      - "8080:8080"

  client:
    build: ./client
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - api

volumes:
  postgres-data:
