version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cmms
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: ./api
    restart: always
    environment:
      DB_URL: jdbc:postgresql://db:5432/cmms
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

  client:
    build: ./client
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - api

volumes:
  postgres-data:
