version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: u898365229_cmms
      MYSQL_USER: u898365229_johntaoum11
      MYSQL_PASSWORD: Jmnhuk123$
      MYSQL_ROOT_PASSWORD: Jmnhuk123$
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: ./api
    restart: always
    environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/u898365229_cmms
    SPRING_DATASOURCE_USERNAME: u898365229_johntaoum11
    SPRING_DATASOURCE_PASSWORD: Jmnhuk123$
    FRONTEND_URL: http://82.25.115.95
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    build: ./client
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - api

volumes:
  mysql-data:
